    /*
    ******************************************************************************
    File: main.c
    Info: Generated by Atollic TrueSTUDIO(R) 9.2.0 2019-04-11

    The MIT License (MIT)
    Copyright (c) 2018 STMicroelectronics

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

    ******************************************************************************
    */

    /* Includes */
#include "stm32f0xx.h"

#include "graphic.h"
#include "matrix_keyboard.h"


int8_t x_cur_pos = 3;
int8_t y_cur_pos = 3;

uint8_t zatychka = 0;

volatile uint8_t buf[8] = {0, 0, 0, 0, 0, 0, 0, 0};

//volatile uint8_t data_flushed = 0;

volatile uint32_t counter = DREBEZG;


uint8_t state = 0, curstate = 0;





void init(void) {

    SysTick->LOAD = 8000000 / 1000 - 1;
    SysTick->VAL = 8000000 / 1000 - 1;
    SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_TICKINT_Msk;


}


void shift_cross(uint8_t change) {
	int8_t x_change = 0, y_change = 0;
	if ((change & 0b00000001) == 0b00000001) {
		--y_change;
	}
	if ((change & 0b00000010) == 0b00000010) {
		++y_change;
	}
	if ((change & 0b00000100) == 0b00000100) {
		++x_change;
	}
	if ((change & 0b00001000) == 0b00001000) {
		--x_change;
	}
	x_cur_pos += x_change;
	y_cur_pos += y_change;
	if (x_cur_pos < 0) {
		x_cur_pos = 7;
	}
	else if (x_cur_pos > 7) {
		x_cur_pos = 0;
	}

	if (y_cur_pos < 0) {
		y_cur_pos = 7;
	}
	else if (y_cur_pos > 7) {
		y_cur_pos = 0;
	}
}


void SysTick_Handler(void) { // SysTick Interrupt handler
	uint8_t change = question();
	if (curstate == change) {
		--counter;
	}
	else {
		curstate = change;
		counter = DREBEZG;
	}
	if (counter == 0) {
		if (state != change) {
			shift_cross(change);
		}
		state = change;
	}
}



int main(void)
{

    init();
    init_keyboard();
    init_graphic();



//    data_flushed = 1;
    draw_buffer();
    for(;;) {
    	for (uint8_t i = 0; i < 8; ++i) {
    		buf[i] = 0;
    	}
    	if (x_cur_pos < 7 && x_cur_pos > 0 && y_cur_pos < 7 && y_cur_pos > 0) {
    		buf[y_cur_pos] = 0b00000111 << (x_cur_pos - 1);
    		buf[y_cur_pos - 1] = 0b00000010 << (x_cur_pos - 1);
    		buf[y_cur_pos + 1] = 0b00000010 << (x_cur_pos - 1);

    	}
    	else if (x_cur_pos < 7 && x_cur_pos > 0) {
    		if (y_cur_pos == 0) {

        		buf[y_cur_pos] = 0b00000111 << (x_cur_pos - 1);
        		buf[y_cur_pos - 1] = 0b00000000 << (x_cur_pos - 1);
        		buf[y_cur_pos + 1] = 0b00000010 << (x_cur_pos - 1);

    		}
    		else {
        		buf[y_cur_pos] = 0b00000111 << (x_cur_pos - 1);
        		buf[y_cur_pos - 1] = 0b00000010 << (x_cur_pos - 1);
        		buf[y_cur_pos + 1] = 0b00000000 << (x_cur_pos - 1);

    		}
    	}
    	else if (y_cur_pos < 7 && y_cur_pos > 0) {
    		if (x_cur_pos == 0) {

        		buf[y_cur_pos] = 0b00000011;
        		buf[y_cur_pos - 1] = 0b00000001;
        		buf[y_cur_pos + 1] = 0b00000001;
    		}
    		else {
        		buf[y_cur_pos] = 0b11000000;
        		buf[y_cur_pos - 1] = 0b10000000;
        		buf[y_cur_pos + 1] = 0b10000000;

    		}
    	}
    	else {
    		if (x_cur_pos == 7 && y_cur_pos == 7) {
        		buf[y_cur_pos] = 0b11000000;
        		buf[y_cur_pos - 1] = 0b10000000;


    		}
    		else if (x_cur_pos == 7 && y_cur_pos == 0) {

        		buf[y_cur_pos] = 0b11000000;

        		buf[y_cur_pos + 1] = 0b10000000;

    		}
    		else if (x_cur_pos == 0 && y_cur_pos == 7) {

        		buf[y_cur_pos] = 0b00000011;
        		buf[y_cur_pos - 1] = 0b00000001;


    		}
    		else if (x_cur_pos == 0 && y_cur_pos == 0) {

        		buf[y_cur_pos] = 0b00000011;

        		buf[y_cur_pos + 1] = 0b00000001;
    		}
    	}
    	set_buffer(buf);

    }



}

