/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-03-21

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

// PA2 PA3 - questioning the keyboard
// PA4 PA5 - result of keyboard

//PA2 = PA15, PA3 = PC12

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

// PA2 PA3 - questioning the keyboard
// PA4 PA5 - result of keyboard

#define DREBEZG 10;

uint8_t state = 0, curstate = 0;

volatile uint32_t counter = DREBEZG;



void init(void) {
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOAEN;
	//RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	//GPIOC->MODER &= ~GPIO_MODER_MODER6;
	GPIOC->MODER |= GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0
				  | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0; // set bit of sixth, 7th & 8th leg

	GPIOC->BSRR = GPIO_BSRR_BR_6 | GPIO_BSRR_BR_8 | GPIO_BSRR_BR_7 | GPIO_BSRR_BR_9; // ALL LEDS OFF 6 7 8 9 reset

	GPIOA->MODER &= ~(GPIO_MODER_MODER4 | GPIO_MODER_MODER5);
	GPIOA->MODER |= GPIO_MODER_MODER15_0;
	GPIOC->MODER |= GPIO_MODER_MODER12_0;
//	GPIOC->ODR |= GPIO_ODR_6; // LED ON


	GPIOA->MODER &= ~GPIO_MODER_MODER0;

	SysTick->LOAD = 8000000 / 1000 - 1;
	SysTick->VAL = 8000000 / 1000 - 1;
	SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_TICKINT_Msk;


	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR4_1 | GPIO_PUPDR_PUPDR5_1 | GPIO_PUPDR_PUPDR15_1;
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR12_1;

}





uint8_t question() {
	uint8_t res = 0;
	GPIOA->BSRR = GPIO_BSRR_BR_15;
	GPIOC->BSRR = GPIO_BSRR_BR_12;

	GPIOA->BSRR = GPIO_BSRR_BS_15;

	__NOP();
	__NOP();
	__NOP();
	if ((GPIOA->IDR & GPIO_IDR_4) == GPIO_IDR_4) {
		res |= 1 << 0;
	}
	if ((GPIOA->IDR & GPIO_IDR_5) == GPIO_IDR_5) {
		res |= 1 << 1;
	}
	__NOP();
	__NOP();

	GPIOA->BSRR = GPIO_BSRR_BR_15;
	GPIOC->BSRR = GPIO_BSRR_BS_12;
	__NOP();
	__NOP();
	__NOP();
	if ((GPIOA->IDR & GPIO_IDR_4) == GPIO_IDR_4) {
		res |= 1 << 2;
	}

	if ((GPIOA->IDR & GPIO_IDR_5) == GPIO_IDR_5) {
		res |= 1 << 3;
	}
	__NOP();
	__NOP();
	GPIOA->BSRR = GPIO_BSRR_BR_15;
	GPIOC->BSRR = GPIO_BSRR_BR_12;
	return res;
}

void SysTick_Handler(void) { // SysTick Interrupt handler
	uint8_t change = question();
	if (curstate == change) {
		--counter;
	}
	else {
		curstate = change;
		counter = DREBEZG;
	}
	if (counter == 0) {
		state = change;
	}
}


void task(uint8_t state_0, uint8_t state_1, uint8_t state_2, uint8_t state_3)
{

	if (state_0 == 0)
		GPIOC->BSRR = GPIO_BSRR_BR_6;
	else
		GPIOC->BSRR = GPIO_BSRR_BS_6;

	if (state_1 == 0)
		GPIOC->BSRR = GPIO_BSRR_BR_8;
	else
		GPIOC->BSRR = GPIO_BSRR_BS_8;

	if (state_2 == 0)
		GPIOC->BSRR = GPIO_BSRR_BR_7;
	else
		GPIOC->BSRR = GPIO_BSRR_BS_7;

	if (state_3 == 0)
		GPIOC->BSRR = GPIO_BSRR_BR_9;
	else
		GPIOC->BSRR = GPIO_BSRR_BS_9;
}


int main(void)
{
	init();

	uint8_t l1 = 0, l2 = 0, l3 = 0, l4 = 0;
	while (1)
	{

		if ((state & (1 << 0)) == (1 << 0)) {
			l1 = 1;
		}
		else l1 = 0;

		if ((state & (1 << 1)) == (1 << 1)) {
			l2 = 1;
		}
		else l2 = 0;

		if ((state & (1 << 2)) == (1 << 2)) {
			l3 = 1;
		}
		else l3 = 0;

		if ((state & (1 << 3)) == (1 << 3)) {
			l4 = 1;
		}
		else l4 = 0;

		task(l1, l4, l2, l3);
	}
}
