/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.2.0   2019-02-21

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"


/* Private macro */
#define COUNTDOWN_INITIAL 15
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

//PC 6-9 - LEDs
//PA0 - button
void init()
{
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN | RCC_AHBENR_GPIOAEN;

	GPIOC->MODER &= ~GPIO_MODER_MODER6;
	GPIOC->MODER |= GPIO_MODER_MODER6_0 | GPIO_MODER_MODER7_0
				  | GPIO_MODER_MODER8_0; // set bit of sixth, 7th & 8th leg
//	GPIOC->ODR |= GPIO_ODR_6; // LED ON
	GPIOC->ODR &= ~GPIO_ODR_6 | ~GPIO_ODR_7 | ~GPIO_ODR_8; // ALL LEDS OFF

	GPIOA->MODER &= ~GPIO_MODER_MODER0;



}


void systick_init() {

	SysTick->LOAD = 2000000 - 1;
	SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;

}


int32_t task(char state_0, char state_1, char state_2, char* button_state)
{

	if (state_0 == 0) {
		GPIOC->ODR &= ~GPIO_ODR_6;
	}
	else
		GPIOC->ODR |= GPIO_ODR_6;

	if (state_1 == 0) {
			GPIOC->ODR &= ~GPIO_ODR_8;
	}
	else
		GPIOC->ODR |= GPIO_ODR_8;

	if (state_2 == 0) {
		GPIOC->ODR &= ~GPIO_ODR_7;
	}
	else
		GPIOC->ODR |= GPIO_ODR_7;

	if ((GPIOA->IDR & GPIO_IDR_0) == 1 && *button_state == 0) // button pressed
	{
		*button_state = 1;
		return 1;
	}
	else
	{
		if (*button_state == 1 && (GPIOA->IDR & GPIO_IDR_0) == 0)
			*button_state = 0;
		return 0;
	}

	return 0;

}

int main(void)
{
	unsigned int countdown = 0;

	int32_t curstate = 0; // 0, 1, 2, 3 - trafficlight states, -1 - all_off
	int32_t curstate_memorised = -1;
	char button_state = 0;
	int8_t state_0 = 1, state_1 = 0, state_2 = 0;
	int32_t task_res;
	init();
  /* Infinite loop */
	systick_init();
	while (1)
	{
		if (countdown == 0)
		{
			countdown = COUNTDOWN_INITIAL;
			curstate = (++curstate_memorised) % 4;
			curstate_memorised = curstate;
			switch (curstate) {
			case 0:
				state_0 = 1;
				state_1 = 0;
				state_2 = 0;
				break;
			case 1:
				state_0 = 1;
				state_1 = 1;
				state_2 = 0;
				break;
			case 2:
				state_0 = 0;
				state_1 = 0;
				state_2 = 1;
				break;
			case 3:
				state_0 = 0;
				state_1 = 1;
				state_2 = 0;
				break;
			}
		}
		if ((countdown <= 6) && (countdown % 2) == 0 && curstate_memorised != 1)
		{
			if (curstate != -1)
			{
				curstate = -1;
			}
			else
			{
				curstate = curstate_memorised;
			}
		}
		if (curstate != -1) {
			task_res = task(state_0, state_1, state_2, &button_state);
		}
		else
			task_res = task(0, 0, 0, &button_state);
		if (task_res == 1)
		{
			if (countdown > 5 && curstate == 0)
			{
				countdown = 5;
			}
			else if (curstate == 2)
			{
				countdown += 5;
			}
		}
		if ((SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk) == SysTick_CTRL_COUNTFLAG_Msk) {
			--countdown;
		}
	}
	return 0;
}
